Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.search.replace("?","\x26").split("\x26gclsrc\x3d").pop().split("\x26").shift()},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Params - gclsrc",collection:"GA4 - Page - Params",
source:"Manage",priv:"false"},{id:"64943"})},64943)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.referrer},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Referrer - URL",collection:"GA4 - Referrer",source:"Manage",priv:"false"},{id:"64902"})},64902)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.search.replace("?","\x26").split("\x26dclid\x3d").pop().split("\x26").shift()},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Params - dclid",collection:"GA4 - Page - Params",source:"Manage",
priv:"false"},{id:"64942"})},64942)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return"G-ZMF24Q2GWK"},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config - LifeLock Web - Measurement ID",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64904"})},64904)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return 2427878879},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config - Norton Web - Stream ID",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64907"})},64907)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.search.replace("?","\x26").split("\x26_gl\x3d").pop().split("\x26").shift()},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Params - _gl",collection:"GA4 - Page - Params",source:"Manage",
priv:"false"},{id:"64944"})},64944)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return"LifeLock Web"},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config - LifeLock Web - Stream Name",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64905"})},64905)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var value="; "+document.cookie;var parts=value.split("; criteo_mm\x3d");if(parts.length==2)return decodeURIComponent(parts.pop().split(";").shift())},transform:function(val){return val?val:""},load:"visitor",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"Criteo_MM_Data_Def",
collection:"User",source:"Manage",priv:"false"},{id:"53038"})},53038)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return 2427878879},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config - LifeLock Web - Stream ID",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64903"})},64903)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.on("click","#submit_button",function(){Bootstrapper.ensEvent.trigger("OL Thank you",this)},true)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return"Norton Web"},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config - Norton Web - Stream Name",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64908"})},64908)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.location.href},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - URL",collection:"GA4 - Page",source:"Manage",priv:"false"},{id:"64910"})},64910)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.location.pathname},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Path",collection:"GA4 - Page",source:"Manage",priv:"false"},{id:"64898"})},64898)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return"G-ZMF24Q2GWK"},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config -Norton Web - Measurement ID",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64906"})},64906)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.search.replace("?","\x26").split("\x26gclid\x3d").pop().split("\x26").shift()},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"GA4 - Page - Params - gclid",collection:"GA4 - Page - Params",
source:"Manage",priv:"false"},{id:"64941"})},64941)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var value="; "+document.cookie;var parts=value.split("; _ga\x3d");if(parts.length==2)return decodeURIComponent(parts.pop().split(";").shift())},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Cookies - _ga",
collection:"GA4 - Page - Cookies",source:"Manage",priv:"false"},{id:"64946"})},64946)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var value="; "+document.cookie;var parts=value.split("; GA4 - Page - Params - gclid\x3d");if(parts.length==2)return decodeURIComponent(parts.pop().split(";").shift())},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Cookies - _gid",
collection:"GA4 - Page - Cookies",source:"Manage",priv:"false"},{id:"64947"})},64947)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.location.hostname},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Domain",collection:"GA4 - Page",source:"Manage",priv:"false"},{id:"64897"})},64897)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var value="; "+document.cookie;var parts=value.split("; _ga_ZMF24Q2GWK\x3d");if(parts.length==2)return decodeURIComponent(parts.pop().split(";").shift())},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Cookies - _ga - LifeLock Web",
collection:"GA4 - Page - Cookies",source:"Manage",priv:"false"},{id:"64948"})},64948)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return 2437003583},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Config - NortonLifeLock Web - Stream ID",collection:"GA4 - Config",source:"Manage",priv:"false"},{id:"64909"})},64909)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.location.hash},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"GA4 - Page - Hash",collection:"GA4 - Page",source:"Manage",priv:"false"},{id:"64901"})},64901)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return window.location.search.replace("?","\x26").split("\x26wbraid\x3d").pop().split("\x26").shift()},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Params - wbraid",collection:"GA4 - Page - Params",
source:"Manage",priv:"false"},{id:"64945"})},64945)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.location.search},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"GA4 - Page - Parameters",collection:"GA4 - Page",source:"Manage",priv:"false"},{id:"64900"})},64900)},-1,-1);