Bootstrapper.bindDependencyDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var inProd=window.flow;if(inProd!=="client")gtag("event","conversion",{"allow_custom_scripts":true,"u1":window.products,"u2":"missing","u3":window.products,"u4":window.total_cart_value,"u7":window.country,"u8":window.language,"u9":window.pagename,"u10":window.program_type,"u11":window.om_program_id,"u12":window.current_subchannel,"u13":window.original_subchannel,
"u14":window.traffic_source,"u15":window.TLT_BILLING_PLAN,"send_to":"DC-8136487/sale/norto000+standard"})},3651737,[3486617],573018,[573014]);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var twitter_id="nuzip";!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments)},s.version="1.1",s.queue=[],u=t.createElement(n),u.async=!0,u.src="//static.ads-twitter.com/uwt.js",a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,"script");twq("init",twitter_id);twq("track","PageView")},3486625,
531757);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var addOn=function(){if(typeof CART_OBJECT_NS==="object")for(var key in CART_OBJECT_NS.cartObject){if(typeof CART_OBJECT_NS.cartObject[key].ItemType!=="undefined")addOn=CART_OBJECT_NS.cartObject[key].ItemType.concat(",")}else addOn="missing";return addOn}();var oldECP=Bootstrapper.Cookies.get("ExistingCustomer");var checkOut="CheckOut\x3dY";if(document.cookie.indexOf("ExistingCustomer")>=1&&
!oldECP.match(/CheckOut/))Bootstrapper.Cookies.set("ExistingCustomer",oldECP+","+addOn+checkOut)},2430023,537030);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var productList=window.products;var productList1=productList.replace(/;+/g,",");var productList2=productList1.replace(/,+/g,",");var productList3=productList2.replace(/^,/,"");var totalPrice=window.total_cart_value;var totalPrice=totalPrice.replace("$","");var event_type="view_cart";var industry="retail";var mt_adid="174308";var mt_id="1080300";var s1=window.current_subchannel;
var currency=window.currency;var page_name=window.pagename;var product_id=productList3;var product_name=CART_OBJECT_NS.cartObject[0].ProductCode;var product_quantity=CART_OBJECT_NS.cartObject[0].Quantity;var product_retail_price=CART_OBJECT_NS.CartTotal;var opt_string="";opt_string+=(page_name?"\x26page_name\x3d"+page_name:"")+(s1?"\x26s1\x3d"+s1:"")+(product_id?"\x26product_id\x3d"+productList3:"")+(product_name?"\x26product_name\x3d"+product_name:"")+(product_quantity?"\x26product_quantity\x3d"+
product_quantity:"")+(product_retail_price?"\x26product_retail_price\x3d"+product_retail_price:"");var url="//"+"pixel.mathtag.com/event/js?mt_pp\x3d1"+"\x26mt_id\x3d"+mt_id+"\x26mt_adid\x3d"+mt_adid+"\x26event_type \x3d"+event_type+opt_string;Bootstrapper.insertScript(url)},3388396,438203);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var s=document.createElement("script");s.async=false;s.src="https://cdn.quantummetric.com/network-interceptor/quantum-norton.js";s.setAttribute("crossorigin","anonymous");document.head.appendChild(s)},3945341,754821);
Bootstrapper.bindDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var updateProductStorage=function(){sessionStorage.orderProducts=JSON.stringify(CART_OBJECT_NS.cartObject);sessionStorage.discPrice=JSON.stringify(CART_OBJECT_NS.CartDiscount)};updateProductStorage()},3989045,372354);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.uetq=window.uetq||[];Bootstrapper.loadScriptCallback("//bat.bing.com/bat.js",function(){var o={"ti":"5441611","q":window.uetq};window.uetq=new UET(o);if(true)window.uetq.push("pageLoad")})},4009623,433869);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var dl="dataLayer";window[dl]=window[dl]||[];var ids=[];ids.push("DC-8136487");ids.push("AW-1043330685");ids.push("DC-4162813");var url="//www.googletagmanager.com/gtag/js?id\x3d"+ids[0]+(dl!=="dataLayer"?"\x26l\x3d"+dl:"");function callbackFunc(){var configProperties={};if("")configProperties.linker={"domains":"".split(",")};for(var i=0;i<ids.length;i++)gtag("config",ids[i],
configProperties)}if(!window.gtag){window.gtag=function(){window[dl].push(arguments)};gtag("js",new Date);Bootstrapper.loadScriptCallback(url,callbackFunc)}else Bootstrapper.loadScriptCallback(url,callbackFunc)},3486617,573014);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(){var qtm=document.createElement("script");qtm.type="text/javascript";qtm.async=1;qtm.src="https://cdn.quantummetric.com/qscripts/quantum-norton.js";var d=document.getElementsByTagName("script")[0];!window.QuantumMetricAPI&&d.parentNode.insertBefore(qtm,d)})()},3921214,640792);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(a,b,c,d,e,f,g){e["ire_o"]=c;e[c]=e[c]||function(){(e[c].a=e[c].a||[]).push(arguments)};f=d.createElement(b);g=d.getElementsByTagName(b)[0];f.async=1;f.src=a;g.parentNode.insertBefore(f,g)})("//d.impactradius-event.com/A247452-16ea-46a1-bf3e-0d9e4518ff9c1.js","script","ire",document,window)},3486618,634741);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var options={},has_valid_value=function(a){return String(typeof a)!=="undefined"&&a!==null&&a!==""},get_cookie=Bootstrapper.Cookies?Bootstrapper.Cookies.get:function(a){var c=document.cookie.split(";");for(var i=0;i<c.length;i++){var b=c[i].trim().split("\x3d");if(a===b[0]){b.shift();return decodeURIComponent(b.join("\x3d"))}}};options.pixel_id="2010787619164716";options.event_data=
{};options.event_data.event_name="PageView";options.event_data.event_id=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var r=Math.random()*16|0,v=c=="x"?r:r&3|8;return v.toString(16)})}();options.event_data.user_data={};options.event_data.custom_data={};options.event_data.data_processing_options=["LDU"];options.event_data.data_processing_options_country=0?parseInt(0,10):0;options.event_data.data_processing_options_state=0?parseInt(0,10):0;if(!options.event_data.user_data.external_id){var pulse_uuid=
get_cookie("uuid");if(pulse_uuid)options.event_data.user_data.external_id=pulse_uuid}!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version="2.0";n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,"script","https://connect.facebook.net/en_US/fbevents.js");fbq.agent="tmensighten";fbq("dataProcessingOptions",
options.event_data.data_processing_options,options.event_data.data_processing_options_country,options.event_data.data_processing_options_state);Bootstrapper.fbq_ids=Bootstrapper.fbq_ids||[];if(!~Bootstrapper.fbq_ids.indexOf(options.pixel_id)){fbq("init",options.pixel_id,options.event_data.user_data);Bootstrapper.fbq_ids.push(options.pixel_id)}fbq["disablePushState\x3dtrue"]="";fbq("set","autoConfig",false,options.pixel_id);fbq("trackSingle",options.pixel_id,options.event_data.event_name,options.event_data.custom_data,
{"eventID":options.event_data.event_id});var sst_options=JSON.parse(JSON.stringify(options)),sha256=function a(b){function c(a,b){return a>>>b|a<<32-b}for(var d,e,f=Math.pow,g=f(2,32),h="length",i="",j=[],k=8*b[h],l=a.h=a.h||[],m=a.k=a.k||[],n=m[h],o={},p=2;64>n;p++)if(!o[p]){for(d=0;313>d;d+=p)o[d]=p;l[n]=f(p,.5)*g|0,m[n++]=f(p,1/3)*g|0}for(b+="\u0080";b[h]%64-56;)b+="\x00";for(d=0;d<b[h];d++){if(e=b.charCodeAt(d),e>>8)return;j[d>>2]|=e<<(3-d)%4*8}for(j[j[h]]=k/g|0,j[j[h]]=k,e=0;e<j[h];){var q=j.slice(e,
e+=16),r=l;for(l=l.slice(0,8),d=0;64>d;d++){var s=q[d-15],t=q[d-2],u=l[0],v=l[4],w=l[7]+(c(v,6)^c(v,11)^c(v,25))+(v&l[5]^~v&l[6])+m[d]+(q[d]=16>d?q[d]:q[d-16]+(c(s,7)^c(s,18)^s>>>3)+q[d-7]+(c(t,17)^c(t,19)^t>>>10)|0),x=(c(u,2)^c(u,13)^c(u,22))+(u&l[1]^u&l[2]^l[1]&l[2]);l=[w+x|0].concat(l),l[4]=l[4]+w|0}for(d=0;8>d;d++)l[d]=l[d]+r[d]|0}for(d=0;8>d;d++)for(e=3;e+1;e--){var y=l[d]>>8*e&255;i+=(16>y?0:"")+y.toString(16)}return i},is_sha256=function(a){return/[0-9a-f]{64}/i.test(a)},_fbp=get_cookie("_fbp"),
_fbc=get_cookie("_fbc");sst_options.timestamp=(new Date).getTime();if(Array.isArray(sst_options.event_data.custom_data.content_type))sst_options.event_data.custom_data.content_type=sst_options.event_data.custom_data.content_type.join(",");for(var i in sst_options.event_data.user_data)if(sst_options.event_data.user_data.hasOwnProperty(i))if(is_sha256(sst_options.event_data.user_data[i]))sst_options.event_data.user_data[i]=[sst_options.event_data.user_data[i]];else{var hashed_value=[sha256(sst_options.event_data.user_data[i])];
sst_options.event_data.user_data[i]=hashed_value}if(_fbp)sst_options.event_data.user_data.fbp=_fbp;if(_fbc)sst_options.event_data.user_data.fbc=_fbc;Bootstrapper.SST=Bootstrapper.SST||[];Bootstrapper.SST.push({name:"facebook_conversions_api_integration",data:sst_options,publishPath:"sst"})},4029959,704319);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var ensVar0=function(){return value};var ensVar1=function(){return currency};var ensVar2=function(){return CART_OBJECT_NS.cartObject[0].ProductCode};var ensVar3=function(){return nortonAnalytics.store_selsku};var cartValue=CART_OBJECT_NS.CartTotal;var value=parseFloat(cartValue);var currency;switch(window.country){case "ae":currency="AED";break;case "fr":currency="EUR";
break;case "de":currency="EUR";break;case "it":currency="EUR";break;case "nl":currency="EUR";break;case "pl":currency="EUR";break;case "es":currency="EUR";break;case "fr":currency="EUR";break;case "ie":currency="EUR";break;case "fi":currency="EUR";break;case "ar":currency="ARS";break;case "au":currency="AUD";break;case "bh":currency="BHD";break;case "br":currency="BRL";break;case "ca":currency="CAD";break;case "ch":currency="CHF";break;case "cl":currency="CLP";break;case "cn":currency="CNY";break;
case "co":currency="COP";break;case "cz":currency="CZK";break;case "dk":currency="DKK";break;case "eg":currency="EGP";break;case "eur":currency="EUR";break;case "gb":currency="GBP";break;case "hk":currency="HKD";break;case "hu":currency="HUF";break;case "id":currency="IDR";break;case "il":currency="ILS";break;case "in":currency="INR";break;case "is":currency="ISK";break;case "jp":currency="JPY";break;case "ke":currency="KES";break;case "kr":currency="KRW";break;case "kw":currency="KWD";break;case "kz":currency=
"KZT";break;case "mx":curren="MXN";break;case "my":currency="MYR";break;case "sg":currency="SGD";break;case "no":currency="NOK";break;case "nz":currency="NZD";break;case "ph":currency="PHP";break;case "ro":currency="RON";break;case "ru":currency="RUB";break;case "se":currency="SEK";break;case "th":currency="THB";break;case "tr":currency="TRY";break;case "tw":currency="TWD";break;case "ua":currency="UAH";break;case "vn":currency="VND";break;case "za":currency="ZAR";break;case "us":currency="USD";break;
default:currency="USD"}console.log("FB AddtoCart");var is_custom_event="AddToCart"==="CustomEvent"?true:false,track_single=true,track_command=["track",track_single?"Single":"",is_custom_event?"Custom":""].join(""),options={},custom_data={},store_event_id=false,enable_capi=true,sst_domain="ensighten.norton.com",sst_publishPath="sst",sst_nexusHost="";options.pixel_id="2010787619164716";options.event_data={};options.event_data.event_name=is_custom_event?"":"AddToCart";if(ensVar0.call(this))custom_data.value=
parseFloat(ensVar0.call(this));if(ensVar1.call(this))custom_data.currency=ensVar1.call(this);if(ensVar2.call(this))custom_data.content_name=ensVar2.call(this);if("")custom_data.content_category="";if(ensVar3.call(this))custom_data.content_ids=ensVar3.call(this)?ensVar3.call(this).split(","):"";if("product")custom_data.content_type="product";if("")custom_data.num_items="";if("")custom_data.search_string="";if("")custom_data.status="";if(store_event_id||enable_capi)options.event_data.event_id=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(c){var r=Math.random()*16|0,v=c=="x"?r:r&3|8;return v.toString(16)})}();options.event_data.custom_data=custom_data;if(enable_capi&&sst_domain){var sst_options=JSON.parse(JSON.stringify(options)),clean=function(obj){for(var key in obj)if(obj.hasOwnProperty(key)&&obj[key]===null||obj[key]===undefined||obj===""||obj[key]==="")delete obj[key];return obj},virtual_browser={page:window.location.href,language:navigator.languages?navigator.languages.join(","):navigator.language,screenDepth:window.screen?
window.screen.colorDepth||window.screen.pixelDepth:undefined,height:window.innerHeight||(document.documentElement?document.documentElement.offsetHeight:undefined),width:window.innerWidth||(document.documentElement?document.documentElement.offsetWidth:undefined),title:document.title,referrer:document.referrer,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,screenHeight:window.screen?window.screen.height:undefined,screenWidth:window.screen?window.screen.width:undefined},settings={nexusHost:Bootstrapper.ensightenOptions.nexus===
"nexus-test.ensighten.com"?"nexus-test.ensighten.com":sst_nexusHost,publishPath:sst_publishPath},get_sst_data=function(){var sst_data={},settings_clean=clean(settings);sst_data.virtualBrowser=clean(virtual_browser);if(Object.keys(settings_clean).length>0)sst_data.settings=settings_clean;sst_data.events=[{name:"facebook_conversions_api_integration",data:sst_options}];return JSON.stringify(sst_data)},build_query_string=function(){var params=["sstVersion\x3d1.0.0"];params.push("sstData\x3d"+encodeURIComponent(get_sst_data()));
return params.join("\x26")};sst_options.event_data=Object.assign(sst_options.event_data,Bootstrapper.fbq);(new Image).src="https://"+sst_domain+"/pc/"+Bootstrapper.ensightenOptions.client+"/sst?"+build_query_string()}if(store_event_id)"";Bootstrapper.bindPageSpecificCompletion(function(){setTimeout(function(){if(!window.fbq){var n=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};window.fbq=n;window._fbq=window._fbq||n;n.push=n;n.loaded=!0;n.version="2.0";n.queue=[];
Bootstrapper.insertScript("https://connect.facebook.net/"+(""||"en_US")+"/fbevents.js")}fbq.agent="tmensighten";track_single?fbq(track_command,options.pixel_id,options.event_data.event_name,options.event_data.custom_data,{"eventID":options.event_data.event_id}):fbq(track_command,options.event_data.event_name,options.event_data.custom_data,{"eventID":options.event_data.event_id})},250)})},4031808,727180);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var type="global",custom_conversion_id="",custom_conversion_label="",custom_event_name="conversion";local_params={};if(type==="async")Bootstrapper.loadScriptCallback("//www.googleadservices.com/pagead/conversion_async.js",function(){window.google_trackConversion({"google_conversion_id":custom_conversion_id,"google_conversion_label":custom_conversion_label,"google_remarketing_only":true,
"google_custom_params":local_params})});else if(type==="sync"){window.google_conversion_id=custom_conversion_id;window.google_conversion_label=custom_conversion_label;window.google_remarketing_only=true;window.google_custom_params=local_params;document.write('\x3cscript src\x3d"//www.googleadservices.com/pagead/conversion.js"\x3e\x3c/script\x3e')}else if(type==="image"){var data=[],dataParam="";for(var i in local_params)if(local_params.hasOwnProperty(i))data.push(encodeURIComponent(i+"\x3d"+local_params[i]));
dataParam=data.length>0?"\x26data\x3d"+data.join(";"):"";(new Image).src="https://googleads.g.doubleclick.net/pagead/viewthroughconversion/"+custom_conversion_id+"/?value\x3d0\x26label\x3d"+custom_conversion_label+"\x26guid\x3dON\x26script\x3d0"+dataParam}else if(type==="global"){var dl="";if(dl=="")dl="dataLayer";window[dl]=window[dl]||[];var remarketingIds=[];remarketingIds.push("AW-1043330685");var url="//www.googletagmanager.com/gtag/js?id\x3d"+remarketingIds[0]+(dl!=="dataLayer"?"\x26l\x3d"+
dl:"");function callbackFunc(){var configProperties={};if("")configProperties.linker={"domains":"".split(",")};for(var i=0;i<remarketingIds.length;i++)gtag("config",remarketingIds[i],configProperties);if(custom_conversion_label){var send_to_list=[];for(var i=0;i<remarketingIds.length;i++){var tracking_id=remarketingIds[i]+"/"+"";send_to_list.push(tracking_id)}local_params.send_to=send_to_list}custom_event_name=custom_event_name?custom_event_name:"conversion";gtag("event",custom_event_name,local_params)}
if(!window.gtag){window.gtag=window.gtag||function gtag(){var dl=""||"dataLayer";window[dl]=window[dl]||[];window[dl].push(arguments)};gtag("js",new Date);Bootstrapper.loadScriptCallback(url,callbackFunc)}else callbackFunc()}},3477313,563003);