Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(new Image).src="https://pt.ispot.tv/v2/TC-3086-2.gif?app\x3dweb\x26type\x3dvisit";(new Image).src="https://pt.ispot.tv/v2/TC-3086-2.gif?app\x3dweb\x26type\x3destore"},3680444,706627);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;!function(w,d){if(!w.rdt){var p=w.rdt=function(){p.sendEvent?p.sendEvent.apply(p,arguments):p.callQueue.push(arguments)};p.callQueue=[];var t=d.createElement("script");t.src="https://www.redditstatic.com/ads/pixel.js",t.async=!0;var s=d.getElementsByTagName("script")[0];s.parentNode.insertBefore(t,s)}}(window,document);rdt("init","t2_cxz0s4qa");rdt("track","AddToCart")},
3748981,683269);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var tagId="2613158642812";var aditionalParams={};aditionalParams.np="ensighten";var email="";if(email)aditionalParams.em=email;if(false)aditionalParams.fp_cookie=false;function callbackFunction(){pintrk("load",tagId,aditionalParams);if(true)pintrk("page")}!function(){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var n=
window.pintrk;n.queue=[],n.version="3.0";var src="https://s.pinimg.com/ct/core.js";Bootstrapper.loadScriptCallback(src,callbackFunction)}}()},3749692,653915);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var custom_params={},queryParams=[];custom_params["ppt"]="22243";custom_params["g"]="norton_signups";custom_params["gid"]="51844";custom_params["ord"]=parseInt(Math.random()*1E9);for(var i in custom_params)if(custom_params.hasOwnProperty(i))queryParams.push(i+"\x3d"+encodeURIComponent(custom_params[i]));var url="https://trkn.us/pixel/c"+"?"+queryParams.join("\x26");(new Image).src=
url},3913512,749592);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(function(){var s=document.createElement("script");s.src="https://tag.havasedge.com/js/evtnc.js";s.async=true;s.setAttribute("data-evtGuid","1bc90753-e6ba-4993-9271-9c1567bb5b4f");s.setAttribute("data-trkGuid","0d24d362-9133-4cf0-8e7e-be8762f0510a");s.setAttribute("data-product_list",CART_OBJECT_NS.cartObject[0].ProductCode);s.setAttribute("data-order_id","missing");s.setAttribute("data-subtotal",
window.total_cart_value);s.setAttribute("data-country","US");document.getElementsByTagName("head")[0].appendChild(s)})();(function(){var s=document.createElement("script");s.src="https://tag.havasedge.com/js/evtnc.js";s.async=true;s.setAttribute("data-evtGuid","5cf27ba5-9ea8-4014-99ea-ec775d2a8e7e");s.setAttribute("data-trkGuid","0d24d362-9133-4cf0-8e7e-be8762f0510a");s.setAttribute("data-product_list","missing");s.setAttribute("data-order_id","missing");s.setAttribute("data-subtotal","missing");
s.setAttribute("data-country","US");document.getElementsByTagName("head")[0].appendChild(s)})()},3862454,706623);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var ensVar0=function(){return(new Date).getTime()};var ensVar1=function(){return window.location.href};var custom_params={},queryParams=[];custom_params["t"]=ensVar0.call(this);custom_params["l"]="tvscientific-pix-o-eb001251-d952-4b93-b92d-f7ac10d97dab";custom_params["u3"]=ensVar1.call(this);for(var i in custom_params)if(custom_params.hasOwnProperty(i))queryParams.push(i+
"\x3d"+encodeURIComponent(custom_params[i]));var url="//tvspix.com/t.png"+"?"+queryParams.join("\x26");(new Image).src=url},3918096,747228);
Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);var isDesktop=!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);var inProd=window.inclient;var promoId=nortonAnalytics.promoid;if(isDesktop){Bootstrapper.insertScript("https://websdk.ujet.co/v2/loader.js");setTimeout(()=>{var createCookie=
function(name,value,secs,cookieDomain){var domain=".norton.com";var expires="";if(secs){var date=new Date;date.setDate(date.getDate()+1);expires=" expires\x3d"+date.toGMTString()+";"}console.log(name+"\x3d"+value+";"+expires+"domain\x3d.norton.com;path\x3d/");document.cookie=name+"\x3d"+value+";"+expires+"domain\x3d.norton.com;path\x3d/"};var getCookie=function(name){const value=`; ${document.cookie}`;const parts=value.split(`; ${name}=`);if(parts.length===2)return parts.pop().split(";").shift()};
var translation={"en":{"ujet_start_title":"","ujet_greeting":"","ujet_message_chat_start":"","ujet_message_queue":"","ujet_channel_chat":"","ujet_chat_title_with_one_agent":"","ujet_chat_title_with_two_agent":"","ujet_chat_transfer_left":""}};var ujet=new UJET({companyId:"1680714333348330579cbe07a4b032143",host:"https://nlok-prod-4l9eze7.uw1.ccaiplatform.com/",lang:"en",translation:translation,menuKey:"NortonSalesChatAgent",customData:{un_entry:{label:"un_entry",value:"hp_home_norton"},un_chattype:{label:"un_chattype",
value:"chatbot"},un_ct:{label:"un_ct",value:nortonAnalytics.site_country},un_lg:{label:"un_lg",value:nortonAnalytics.site_language}},logo:"https://support.norton.com/sp/static/external/assets/images/vulcan/ccai/NortonCheckmark.png",style:{"--chat-bubble-border":"#feeb29","--chat-input-default-text":"#242424","--dialog-button-default-background":"#feeb29","--dialog-button-focus-background":"#feeb29","--dialog-button-focus-border":"#242424","--dialog-button-focus-label":"#242424","--dialog-button-focus-outline":"#242424",
"--dialog-button-hover-background":"#fff388","--dialog-button-hover-border":"#242424","--dialog-button-hover-label":"F4F1ED","--link-button-light-default-label":"#242424","--link-button-light-hover-label":"#242424","--link-button-light-active-label":"#5E5E5E","--link-button-light-focus-label":"#5E5E5E","--link-color":"#0f71f0","--primary-font":"Inter, sans-serif","--primary-color":"#feeb29",links:["https://fonts.googleapis.com/css2?family\x3dInter:wght@200;300;400;500;600;700;800\x26display\x3dswap"]},
launcher:{cssText:".wrap button{background:#feeb29}",chatIcon:"https://support.norton.com/sp/static/external/assets/images/vulcan/ccai/Chat_icon_E.png",style:{"--background-color":"#feeb29","--icon-color":"#242424"}},cobrowseOptions:{api:"https://nlok-prod-4l9eze7.cobrowse.uw1.ccaiplatform.com",license:"xfo0-SNNXtuyyQ",trustedOrigins:["https://nlok-prod-4l9eze7.cobrowse.uw1.ccaiplatform.com"]}});ujet.on("created",function(){ujet.authenticate(getAuthToken);createCookie("isChatOpen","yes");console.log("chat started")});
ujet.on("close",function(){createCookie("isChatOpen","no");console.log("chat ended")});if(getCookie("isChatOpen")==="yes")ujet.start();ujet.on("chat:update",(chat)=>{if(chat.status==="assigned"&&chat.id){var obj='"chat status:'+chat.status+",chat_id:"+chat.id+",end_user_id:"+chat.end_user.id+",agent_id:"+chat.agent.id+'"';createCookie("ccai_chat_details",obj.replace(/^'|'$/g,""),24*86400);createCookie("ccai_chat_details",obj.replace(/^'|'$/g,""),24*86400);console.log("getCookie(ccai_chat_unique) : "+
getCookie("ccai_chat_unique"));if(getCookie("ccai_chat_unique")!==chat.id+"_"+chat.end_user.id&&chat.status==="assigned"){gtag("event","chat_started",{"send_to":"G-FG3M2ET3ED"});createCookie("ccai_chat_unique",chat.id+"_"+chat.end_user.id,24*86400)}}});async function getAuthToken(){var ctt=getCookie("ctt");var response=await fetch("/estore/rest/api/v1/api/ccai/auth/token?ctt\x3d"+ctt,{headers:{"Content-Type":"application/json"},method:"GET"});const result=await response.json();createCookie("ctt",
result.ctt,36E5);return result}},2E3)}else console.log("Mobile")},4046223,761847);Bootstrapper.bindDOMLoaded(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;(new Image).src="//ct.pinterest.com/v3/?tid\x3d2613158642812"+"\x26"+"event\x3dAddToCart"+"\x26"+"value\x3d"+CART_OBJECT_NS.CartTotal+""+"\x26"+"order_quantity\x3d"+CART_OBJECT_NS.cartObject[0].Quantity+""},3748828,679822);